# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'YJDataCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'FMDB'
  # Pods for YJDataCenter
  target 'YJDataCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
